project:
  type: website
  output-dir: docs

website:
  title: "Midterm Project"
  navbar:
    left:
    - href: index.qmd
      text: Lina's Main Page
    - href: about.qmd
      text: Lina's Codes
    - href: dummy.qmd
      text: Lina's References
    - href: mid_proj.html
      text: Blake's Main Page
    - href: mid-proj-codes.html
      text: Blake's Codes

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

