project:
  type: website
  output-dir: docs

website:
  title: "Midterm Project"
  navbar:
    left:
    - href: index.qmd
      text: Main Page
    - href: about.qmd
      text: Codes
    - href: dummy.qmd
      text: References

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

